on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.4"
          
      - name: Print Bun Version
        run: bun version
        
      - name: Install Dependencies
        run: bun install

      - name: Run Check
        run: bun run local:check

      - name: Generate Kcc Binary
        run: bun run prod:gen

      
        
