on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.4"

      - name: Print Bun Version
        run: bun version

      - name: Install Dependencies
        run: bun install

      - name: Run check
        run: bun local:check

      - name: Generate Kcc Binary
        run: bun prod:gen
